dataset_name: 'ncfm'
dataset_root_path: '../../data/ncfm'
df_train: 'train.csv'
df_trainval: fish.csv
df_val: 'val.csv'
df_test: 'val.csv'
folder_train: 'train'
folder_val: 'train'
folder_test: 'train'
df_classid_classname: 'classid_classname.csv'
